# Builds the site and deploys it.
name: Build and Deploy

# Triggers the workflow on push for the master branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: setup
        run: yarn install

      - name: build
        run: yarn build

      - name: verify built output
        run: find build/ -print

      - name: deploy via FTP
        run: node ftp-deploy
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
